### ISSUE TITLE
/msg message buggy if sender has flair

### ISSUE THREAD

**Issue by sylae** [calref/cadence#14]
![Like so](https://c312441.ssl.cf1.rackcdn.com/sylae/images/misc/96e78337970062eeeca67306761cf84b.png)

**Comment by cburschka** [comment]
Once cburschka/cadence#223 is fixed, the CSS should be updated here too.

With the new classes, it looks like 

``` css
.jid-node-sylae.user-show-default  {
  background: url('https://c312441.ssl.cf1.rackcdn.com/chat/img/flair/jid-node-sylae.png') no-repeat scroll left center transparent;
  padding-left: 20px;
}
```

already does the right thing.
